strict_front_matter: true
timezone: America/Detroit

repository: mgsisk/usatkdmi.com

theme: null
title: USA Tae Kwon Do
url: https://usatkdmi.com
baseurl: /
description: >
  Build self-confidence, self-esteem, and learn self-defense while you get fit,
  lose weight, and have fun at USA Tae Kwon Do. **Be strong!**

defaults:
  - scope:
      path: ""
    values:
      layout: default
      alert:
        url: https://usatkdmichamp2025.eventbrite.com
        msg: Get ready for the USA Tae Kwon Do Championships

include:
  - _pages

exclude:
  - CODEOWNERS
  - Dockerfile
  - LICENSE.md
  - node_modules
  - package-lock.json
  - package.json
