title: USA Tae Kwon Do
description: >
  Build self-confidence, self-esteem, and learn self-defense while you get fit,
  lose weight, and have fun at USA Tae Kwon Do. **Be strong!**
url: https://usatkdmi.com
permalink: /events/:title
include:
  - _pages

safe: true

defaults:
  - scope:
      path: ''
    values:
      layout: default
      alert:
        url: https://usatkdmichamp2023.eventbrite.com
        msg: Get ready for the 2023 USA Tae Kwon Do Championships
